### ISSUE TITLE
Deployment configs in RBAC role for site controller

### ISSUE THREAD

**Issue by rmallam** [skupperproject/skupper#1067]
Deployment configs are missing in the Role that is created for site controller. Could you add it ?

https://github.com/skupperproject/skupper/blob/master/cmd/site-controller/deploy-watch-current-ns.yaml 

I made this change to get this going for our application

```
- apiGroups:
  - ""
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
```
