### ISSUE TITLE
 skupper-service-controller oauth-proxy service account token

### ISSUE THREAD

**Issue by chassing** [skupperproject/skupper#1090]
As long as skupper doesn't support native prometheus metrics #951, I would like to fetch `/DATA` from the skupper-service-controller by myself to do minimal skupper service monitoring.
Currently, the oauth proxy in front of the skupper-service-controller isn't configured to support authentication via kubernetes service account tokens, which makes it impossible to consume :( For example, the cluster internal prometheus accepts authentication via service account tokens via this configuration:

```yaml
- '-openshift-sar={"resource": "namespaces", "verb": "get"}'
- '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
```

See https://github.com/openshift/oauth-proxy#delegate-authentication-and-authorization-to-openshift-for-infrastructure for details

My skupper config is:

```yaml
  controller-memory-limit: 128Mi
  controller-pod-antiaffinity: skupper.io/component=controller
  router-cpu: 200m
  router-memory: 156Mi
  controller-cpu-limit: 500m
  router-service-annotations: managed-by=qontract-reconcile
  routers: '3'
  name: obs-rhobs-appsres03ue1-app-sre-observability-stage
  console-authentication: openshift
  controller-memory: 128Mi
  router-cpu-limit: 500m
  service-sync: 'true'
  router-console: 'false'
  router-memory-limit: 156Mi
  service-controller: 'true'
  ingress: route
  router-pod-antiaffinity: skupper.io/component=router
  console: 'true'
  controller-cpu: 200m
  cluster-local: 'false'
  controller-service-annotations: managed-by=qontract-reconcile
  router-logging: error
  edge: 'false'
  console-ingress: route
```
