### ISSUE TITLE
Various parameters in site config-map are ignored when using YAML files

### ISSUE THREAD

**Issue by nice-pink** [skupperproject/skupper#1122]
I'm using skupper with argo cd and therefore got it installed via yaml manifests. It works pretty neat, but various of the parameters in the site config map are ignored.

I try to update:
- router-cpu
- router-memory
- routers
- router-service-annotations

But none of the above have any effect.

Some parameters work as expected, like:
- name
- edge
- console
- ...

Config map:
```
apiVersion: v1
data:
  cluster-local: "false"
  console: "true"
  console-authentication: internal
  edge: "false"
  name: default
  router-console: "true"
  router-cpu: 500m
  router-memory: 1Gi
  routers: '3'
  router-service-annotations: "cloud.google.com/network-tier:Standard"
  service-controller: "true"
  service-sync: "true"
kind: ConfigMap
metadata:
  name: skupper-site
```
