### ISSUE TITLE
Support for traefik IngressRouteTCP as ingress type

### ISSUE THREAD

**Issue by roberto-iannone-riatlas** [skupperproject/skupper#1221]
Probably someone uses traefik as ingress-controller and wish to allow skupper to works with it.

## Failed attempts
I tried to use `--ingress=ingress` and specify as annotation the traefik ingressClass with `--ingress-annotations=kubernetes.io/ingress.class=traefik` and define a custom ingress for all the skupper services. Unfortunately this not works because traefik by default not enable ssl-passthrough and I want to not change it. 
The solution seems to be to define IngressRouteTCP instead of a simple Ingress (with annotations). But skupper do not support it.
I found a workaround but it could be useful if skupper will support it natively.

## Contour CRDs workaround
For people that uses traefik and not want a new loadbalancer to be spawned by the cloud provider I did this trick:
1. install only the CRDs of Contour using
```
kubectl apply -f https://raw.githubusercontent.com/projectcontour/contour/main/examples/contour/01-crds.yaml
```
2. install skupper with flags  `--ingress=contour-http-proxy`  and `--ingress-host="<your domain>"`
```
skupper init --ingress=contour-http-proxy --ingress-host="example.com"
```
skupper will create all the necessary HTTPProxy resource

3. use the virtualhost defined into HTTPProxy resources and create a IngressRouteTCP for traefik
```
kubectl apply -f -<<"EOF"
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: skupper
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`skupper-claims.default.example.com`)
    services:
    - name: skupper
      port: 8081
  - match: HostSNI(`skupper-console.default.example.com`)
    services:
    - name: skupper
      port: 8010
  - match: HostSNI(`skupper-inter-router.default.example.com`)
    services:
    - name: skupper-router
      port: 55671
  - match: HostSNI(`skupper-edge.default.example.com`)
    services:
    - name: skupper-router
      port: 45671
  tls:
    passthrough: true
EOF
```
If you use different namesapce replace `default` with the namespace where you installed skupper.
Hope this can help .. hope skupper will support IngressRouteTCP natively in the future :)
