### ISSUE TITLE
Kube adaptor accumulates connections to the router

### ISSUE THREAD

**Issue by ted-ross** [skupperproject/skupper#2106]
**Describe the bug**
The kube-adaptor's config-sync function occasionally opens new connections to the router but does not appear to ever close those connections.  As a result, over time many open connections are present..

**How To Reproduce**
Create a simple site via CR in a namespace.  Then create a RouterAccess to open a listener on the router.  Delete and re-add this RouterAccess several times.  Observe via the router log or 'skstat -c' the accumulation of connections.

**Expected behavior**
I expect kube-adaptor to open and use a single connection for router management.  If there's any reason to open a new connection, older connections should be closed.

**Environment details**
 - Skupper CLI: N/A
 - Skupper Operator (if applicable): 2.0.0
 - Platform: Minikube on Fedora

**Additional context**

My site and router-access yamls:

```
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: test
spec:
  linkAccess: default
```

```
---
apiVersion: skupper.io/v2alpha1
kind: Certificate
metadata:
  name: skupper-local-server-custom
spec:
  ca: skupper-local-ca
  hosts:
  - skupper-local-server-custom
  server: true
  subject: skupper-local-server-custom
---
apiVersion: skupper.io/v2alpha1
kind: RouterAccess
metadata:
  name: testaccess
spec:
  roles:
    - name: normal
      port: 10001
  tlsCredentials: skupper-local-server-custom
```
