### ISSUE TITLE
Headless service support in Skupper V2

### ISSUE THREAD

**Issue by Jdelachi** [skupperproject/skupper#2144]
**Describe the bug**
In Skupper V1.x is support to expose a headless service, but in Skupper V2 this option is not available.

**How To Reproduce**
Feature not implemented -> `skupper listener create backend 8080 --headless`

**Expected behavior**
Be able to expose a headless service using Skupper V2.
`skupper listener create backend 8080 --headless`

**Environment details**
 - Skupper CLI: 2.0.0
 - Skupper Operator (if applicable): 2.0.0
 - Platform: kubernetes

**Comment by c-kruse** [comment]
Hi @Jdelachi. You are correct that this is not an option in skupper V2.

There is a feature in V2 called **exposePodsByName** that we intend to be a replacement for most use cases that the --headless option was used for in V1.

Afraid I don't have a suitable example to share quite yet, but the gist of it is this. When the `exposePodsByName` flag is set on a Connector (workload side) and a Listener (client side) with a matching routing key, skupper will create a Service in the Listener Site for each Pod that the Connector(s) target. This way each pod can be individually addressed.

```
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: backend
spec:
  port: 8080
  routingKey: backend
  selector: app=backend
  type: tcp
  exposePodsByName: true
```

```
apiVersion: skupper.io/v2alpha1
kind: Listener
metadata:
  name: backend
spec:
  host: backend
  port: 8080
  routingKey: backend
  type: tcp
  exposePodsByName: true
```

```
## using kubeconfig for the workload-side site
$ kubectl get pods -l app=backend
NAME                      READY   STATUS    RESTARTS   AGE
backend-76cbb78c6-bcgsp   1/1     Running   0          2m27s
backend-76cbb78c6-jpq7n   1/1     Running   0          2m27s
```

```
## using kubeconfig for the client-side Site
$ kubectl get svc
NAME                      TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                           AGE
backend                   ClusterIP      10.96.80.2      <none>           8080/TCP                          2m57s
backend-76cbb78c6-bcgsp   ClusterIP      10.96.141.80    <none>           8080/TCP                          2m12s
backend-76cbb78c6-jpq7n   ClusterIP      10.96.93.27     <none>           8080/TCP                          2m12s
...
```
