### ISSUE TITLE
RouterAccess cannot create "normal" ingresses

### ISSUE THREAD

**Issue by ted-ross** [skupperproject/skupper#2161]
**Describe the bug**
RouterAccess only honors "inter-router" and "edge" roles for router listeners.  It should also be usable for "normal" role listeners/ingresses.

**How To Reproduce**
Apply the following yaml to a running V2 site:
```
apiVersion: skupper.io/v2alpha1
kind: RouterAccess
metadata:
  name: test-access
spec:
  generateTlsCredentials: true
  issuer: skupper-site-ca
  roles:
  - name: normal
    port: 20002
  tlsCredentials: skupper-site-server
```

**Expected behavior**
I expect an ingress to be created for test-access and the router configuration to be updated with a normal-mode listener on port 20002.

The ingress _is_ created, but the listener is not.

**Environment details**
 - Skupper CLI: N/A
 - Skupper Operator (if applicable): main branch (6a81e6f62c06217642aa5172b7a4b6408d208aa4)
 - Platform: Openshift

**Additional context**
None.
