### ISSUE TITLE
Service Controller stuck in Pending state when skuppering multiple namespaces

### ISSUE THREAD

**Issue by Kampe** [skupperproject/skupper#372]
Found this issue when simulating our edge environments on a VM and attempting to add another namespace's services to be skuppered from our cloud hub (we have services in monitoring and in other namespaces we're attempting to gain access to on our edge sites).

The service controller that rolls out first will claim the ports, and attempt to establish an External IP with a loadbalancer from klipper-lb, it seems when you have more then one service controller in a cluster you have potential to run into a collision on 8080.  I noticed this appear as a race condition for the site-controller as it will typically manage to deploy the first defined, but not the second namespace, so I started staggering the configmap rollouts and uncovered this. 

```
Name:           svclb-skupper-controller-m7g47
Namespace:      monitoring
Priority:       0
Node:           <none>
Labels:         app=svclb-skupper-controller
                controller-revision-hash=794fc5cc97
                pod-template-generation=1
                svccontroller.k3s.cattle.io/svcname=skupper-controller
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  DaemonSet/svclb-skupper-controller
Containers:
  lb-port-8080:
    Image:      rancher/klipper-lb:v0.1.2
    Port:       8080/TCP
    Host Port:  8080/TCP
    Environment:
      SRC_PORT:    8080
      DEST_PROTO:  TCP
      DEST_PORT:   8080
      DEST_IP:     10.43.94.109
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fb2hl (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  default-token-fb2hl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-fb2hl
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly op=Exists
                 node-role.kubernetes.io/master:NoSchedule op=Exists
                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  13m   default-scheduler  0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports.
  Warning  FailedScheduling  13m   default-scheduler  0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports.
  ```
  
using this for configuration:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: skupper-site
  namespace: default
data:
  cluster-local: "false"
  console: "false"
  edge: "true"
  name: edge
  router-console: "false"
  service-controller: "true"
  service-sync: "true"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: skupper-site
  namespace: monitoring
data:
  cluster-local: "false"
  console: "false"
  edge: "true"
  name: edge
  router-console: "false"
  service-controller: "true"
  service-sync: "true"

```
