### ISSUE TITLE
Bug: Updating site-controller with new versions of assets

### ISSUE THREAD

**Issue by Kampe** [skupperproject/skupper#379]
Mostly a bug, but somewhat a feature request.  When filling out that last report I noticed there was a new bugfix version, so I went to deploy it to ensure the issue I was facing is still an issue at all and am in this state currently.  When rolling new versions to be deployed to the site controller via yaml, after the site controller updates itself and restarts, it never actually updates the deployed resources (routers, service controller) with the version specified in the site controller's variables.

Deployed Manifest:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-site-controller
  namespace: skupper-site-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      application: skupper-site-controller
  template:
    metadata:
      labels:
        application: skupper-site-controller
    spec:
      serviceAccountName: skupper-site-controller
      containers:
      - name: site-controller
        image: quay.io/skupper/site-controller:0.4.0
        env:
        - name: SKUPPER_SERVICE_CONTROLLER_IMAGE
          value: quay.io/skupper/service-controller:0.4.0
```

Then, deployed this manifest:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-site-controller
  namespace: skupper-site-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      application: skupper-site-controller
  template:
    metadata:
      labels:
        application: skupper-site-controller
    spec:
      serviceAccountName: skupper-site-controller
      containers:
      - name: site-controller
        image: quay.io/skupper/site-controller:0.4.2
        env:
        - name: SKUPPER_SERVICE_CONTROLLER_IMAGE
          value: quay.io/skupper/service-controller:0.4.2
```

The only way to redeploy is to bounce the services manually I do believe.
