### ISSUE TITLE
connection token secret not being populated

### ISSUE THREAD

**Issue by Kampe** [skupperproject/skupper#537]
Hello!

When creating a secret to be populated as a connection token, we're not seeing those secrets ever get populated with their connection information.

Here's an example of the yaml we use to describe the secret:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: skupper-site-token
  namespace: logging
  labels:
    skupper.io/type: connection-token-request
 ```
 
 we see logs such as these below coming from the site-controller:
 ```
 2021/07/29 20:34:25 Failed to generate token for request skupper-site-token: configmaps "skupper-internal" not found
 ```
 
 The site controller role looks as such:
 ```
 apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    application: skupper-site-controller
  name: skupper-site-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - pods/exec
  - services
  - secrets
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  
  ```
 

 
 Let us know if there's anything else we can provide! Thanks!

**Comment by grs** [comment]
What version is this with?

**Comment by ted-ross** [comment]
Nick,

You have to have the skupper-site-controller pod running for this to work.
There's a yaml referenced in the docs that installs the site-controller for
your namespace (or for all namespaces).

https://skupper.io/docs/declarative/tutorial.html#step-2-create-a-skupper-site-in-each-namespace

-Ted

**Comment by grs** [comment]
I did find and fix an issue that would cause this. Should be included in the upcoming 0.7.0.

**Comment by waldner** [comment]
Am I wrong or this used to work with skupper 0.6.0? If so, why was this functionality removed?

**Comment by grs** [comment]
It worked at some point, but there was an unintentional regression. It should be working from 0.7.0 again.

**Comment by waldner** [comment]
Thanks. Doesn't seem to work in 0.8.1. My workflow is: create the following secret before skupper is running (for reasons outside the scope of this), in the same namespace that skupper will use:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: skupper-secret
  namespace: logging
  labels:
    skupper.io/type: connection-token-request
```

With 0.6.0, when skupper booted it somehow noticed the secret and populated it with `ca.crt`, `tls.crt` and `tls.key`. With 0.8.1 this seems to not work anymore, and the above secret needs to be created after skupper has booted. I just wanted to confirm that this is working as expected and if so why the difference.
