### ISSUE TITLE
Site Controller Crashes on upgrade to 0.8.1

### ISSUE THREAD

**Issue by Kampe** [skupperproject/skupper#639]
After migration from 0.7.0 - 0.8.1 we're left with this error:
```
2021/11/18 04:13:39 Skupper site controller watching all namespaces
2021/11/18 04:13:39 Version: 0.8.1
2021/11/18 04:13:39 Starting the Skupper site controller informers
2021/11/18 04:13:39 Waiting for informer caches to sync
2021/11/18 04:13:39 Checking if sites need updates (0.8.1)
E1118 04:13:42.615062       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14a7280, 0x22f5f50)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x14a7280, 0x22f5f50)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/skupperproject/skupper/client.setAndWaitControllerReplicas(0xc000356000, 0xc000000000, 0x2, 0x2, 0x3)
        /go/src/app/client/router_update.go:573 +0xf0
github.com/skupperproject/skupper/client.(*VanClient).RouterUpdateVersionInNamespace(0xc000356000, 0x1878820, 0xc000044230, 0x0, 0xc0002faa09, 0x7, 0xc0003ffdd8, 0xc0000a6000, 0x26)
        /go/src/app/client/router_update.go:445 +0x28e5
main.(*SiteController).updateChecks(0xc000293600)
        /go/src/app/cmd/site-controller/controller.go:393 +0xff
main.(*SiteController).Run(0xc000293600, 0xc00008e660, 0x0, 0x0)
        /go/src/app/cmd/site-controller/controller.go:119 +0x2ee
main.main()
        /go/src/app/cmd/site-controller/main.go:64 +0x1c6
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1330920]

goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x14a7280, 0x22f5f50)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/skupperproject/skupper/client.setAndWaitControllerReplicas(0xc000356000, 0xc000000000, 0x2, 0x2, 0x3)
        /go/src/app/client/router_update.go:573 +0xf0
github.com/skupperproject/skupper/client.(*VanClient).RouterUpdateVersionInNamespace(0xc000356000, 0x1878820, 0xc000044230, 0x0, 0xc0002faa09, 0x7, 0xc0003ffdd8, 0xc0000a6000, 0x26)
        /go/src/app/client/router_update.go:445 +0x28e5
main.(*SiteController).updateChecks(0xc000293600)
        /go/src/app/cmd/site-controller/controller.go:393 +0xff
main.(*SiteController).Run(0xc000293600, 0xc00008e660, 0x0, 0x0)
        /go/src/app/cmd/site-controller/controller.go:119 +0x2ee
main.main()
        /go/src/app/cmd/site-controller/main.go:64 +0x1c6
  ```

**Comment by grs** [comment]
Should be fixed in 0.8.2 (https://raw.githubusercontent.com/skupperproject/skupper/0.8/cmd/site-controller/deploy-watch-all-ns.yaml)

**Comment by Kampe** [comment]
So if we change the site controller version to 0.8.3 via this yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-site-controller
  namespace: skupper-site-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      application: skupper-site-controller
  template:
    metadata:
      labels:
        application: skupper-site-controller
    spec:
      serviceAccountName: skupper-site-controller
      containers:
      - name: site-controller
        image: quay.io/skupper/site-controller:0.8.3
        env:
        - name: SKUPPER_SERVICE_CONTROLLER_IMAGE
          value: quay.io/skupper/service-controller:0.8.3
```

this will force the rollout of the new version?
