### ISSUE TITLE
Policies for network and services 

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#655]
# Design

Introduce a Custom Resource Definition (CRD) to allow managing cluster level Skupper policies.

# Type

## SkupperClusterPolicy (CRD)

Defines cluster level policies for Skupper.

# Fields

## SkupperClusterPolicy specific fields

```
    Namespaces []string // regex and label expressions allowed

    ### Network control attributes
    AllowIncomingLinks            bool
    AllowedOutgoingLinksHostnames []string // allowed hostnames for outgoing links (regex allowed)

    ### Service control attributes
    AllowedExposedResources []string // format: <resource type>/<name>
    AllowedServices         []string // service names - regex allowed
```

# Fields Description

## Namespaces

List of namespaces to which the SkupperClusterPolicy applies to.
You can use '*', regular expressions and label expressions.

Type:    `[]string`\
Default: `[]`

## AllowIncomingLinks

Defines whether or not Skupper allows incoming links.

Type:    `Boolean `\
Default: `false`

## AllowedOutgoingLinksHostnames

List of allowed hostnames for outgoing links.
It accepts '*' and regular expressions

Type:    `[]string`\
Default: `[]`

## AllowedExposedResources

List of resources that can be exposed through. Resources must be
defined using the `[resource]/[name]` convention.

If empty, you will not be able to expose resources.
You can use `["*"]` to allow exposure of any resource.

Type:    `[]string`\
Default: `[]`

## AllowedServices

List of service names (regex) that can be created locally by Skupper.
It helps controlling which _service_ can be created in the respective namespaces.
It also controls services that can be imported from other namespaces.

If empty, services exposed through Skupper will not be created in the respective namespaces.
You can use `["*"]` to allow the creation of any remote service.
It allows '*' and regular expressions.

Type:    `[]string`\
Default: `[]`

# Samples

## Allow everything, but link creation for all namespaces

```
apiVersion: skupper.io/v1alpha1
kind: SkupperClusterPolicy
metadata:
  name: cluster-policy-sample-01
spec:
  namespaces:
    - "*"
  allowIncomingLinks: true
  allowedExposedResources:
    - "*"
  allowedOutgoingLinksHostnames: []
  allowedServices:
    - "*"
```

## Allow specific services to be created on defined namespaces

```
apiVersion: skupper.io/v1alpha1
kind: SkupperClusterPolicy
metadata:
  name: cluster-policy-sample-02
spec:
  namespaces:
    - "ns1"
    - "ns2"
    - "ns3"
  allowedServices:
    - "my-app-a"
    - "my-app-b"
```

### Allow everything on specific namespaces

```
apiVersion: skupper.io/v1alpha1
kind: SkupperClusterPolicy
metadata:
  name: cluster-policy-sample-03
spec:
  namespaces:
    - "ns4"
    - "ns5"
    - "ns6"
  allowIncomingLinks: true
  allowedOutgoingLinksHostnames: ["*"]
  allowedExposedResources: ["*"]
  allowedServices: ["*"]
```

# Proposed changes

SkupperClusterPolicy changes will be detected by the Service Controller (policy controller).
If cluster level permission to read SkupperClusterPolicies is granted to the
Service Controller it will also track it, or generate an event stating it is not
allowed to monitor SkupperClusterPolicy and so policies will not be supported. Controller
will also log whether or not policy is allowed.

It will also provide a Rest API for policy validation. This API can be used by the
CLI, through the `get` command, or by the Console in the future.

# Impacts

- Service controller
  - Policy controller that watches SkupperClusterPolicies
  - APIs for policy validation:
    - /policy/incominglink
    - /policy/outgoinglink/{hostname}
    - /policy/expose/{resourceType}/{resourceName}
    - /policy/service/{name}
  - Service Sync to validate if service name can be created
  - GET command to include subcommands for policy
  - CLI to validate /policy API before performing actions
    - service create/bind
    - expose
    - token create
    - link create
    - gateway init
  - API used by console to verify policies
  - Definition monitor validates if services and resources are allowed
  - Connected links that are no longer allowed will be disconnected
  - Exposed resources that are no longer allowed will be unbound
  - Services that are no longer allowed will be removed
