### ISSUE TITLE
Wrong host in connection token

### ISSUE THREAD

**Issue by HagaiBarel** [skupperproject/skupper#662]
Hello,

I'm setting up `skupper` with `nginx-ingress` and it seems that the created hosts in the link token don't match the hosts in the site ingress resource. 

For example, let's say I set `ingress-host = example.com` and using the `monitoring` namespace (obviously the real domain is something different)

The ingress:

```
Name:             skupper
Labels:           <none>
Namespace:        monitoring
Address:          XX.XXX.X.XXX
Default backend:  default-http-backend:80 (10.200.0.3:8080)
Rules:
  Host                                           Path  Backends
  ----                                           ----  --------
  claims.monitoring.example.com        
                                                 /   skupper:8081 (10.200.2.38:8081)
  console.monitoring.example.com       
                                                 /   skupper:8080 (10.200.2.38:8080)
  inter-router.monitoring.example.com  
                                                 /   skupper-router:55671 (10.200.0.67:55671)
  edge.monitoring.example.com          
                                                 /   skupper-router:45671 (10.200.0.67:45671)
Annotations:                                     kubernetes.io/ingress.class: nginx
                                                 nginx.ingress.kubernetes.io/ssl-passthrough: true
                                                 nginx.ingress.kubernetes.io/ssl-redirect: true
Events:                                          <none>
```

But the created token secret contains the following annotations:

```yaml
annotations:
    edge-host: skupper-edge.monitoring.example.com
    edge-port: "443"
    inter-router-host: skupper-inter-router.monitoring.example.com
    inter-router-port: "443"
    skupper.io/generated-by: c25f5f82-7072-41db-9198-ac96fb57cccd
    skupper.io/site-version: 0.8.4
```

The hosts are prefixed with `skupper-` and this results in sites unable to find the right host to connect to. When I remove the prefix, (e.g. `edge-host: edge.monitoring.example.com`) everything works fine
