### ISSUE TITLE
Are annotations supported for `ExternalName` services?

### ISSUE THREAD

**Issue by waldner** [skupperproject/skupper#672]
As the subject says (or, are annotations supported for services at all, even).

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    skupper.io/proxy: "tcp"
    skupper.io/address: "my-service"
    skupper.io/port: "443"
spec:
  type: ExternalName
  externalName: "example.com"
```

I see skupper connecting to the core cluster, but no service is exposed.

**Comment by grs** [comment]
Annotations are supported on Services. However at present they do not work on an ExternalService. What you can do however is create a second Service that targets the ExternalName service, e.g.

```
apiVersion: v1
kind: Service
metadata:
  name: my-skupper-service
  annotations:
    skupper.io/proxy: "tcp"
    skupper.io/target: "my-service"
spec:
    ports:
    ....
```
Requests to this second service will be redirected to the externalname defined.
