### ISSUE TITLE
expose service type externalName

### ISSUE THREAD

**Issue by quentinalbertone** [skupperproject/skupper#688]
Hi, 

first of all, thanks for skupper, I really like it

I want to manage edge kubernetes with argocd, and I would like to expose the `kubernetes.default.svc.cluster.local` but from another namespace.
Is it possiblle to expose this service through skupper

```Yaml
apiVersion: v1
kind: Service
metadata:
  name: my-kubernetes
spec:
  type: ExternalName
  externalName: kubernetes.default.svc.cluster.local
  ports:
    - port: 443
```

or only deployments can be exposed ? 

Thanks

**Comment by grs** [comment]
You should be able to expose that by adding a service like the following to a namespace with skupper running in it:

```
apiVersion: v1
kind: Service
metadata:
  name: my-kubernetes
  annotations:
    skupper.io/proxy: tcp
    skupper.io/target: kubernetes.default.svc.cluster.local
spec:
  ports:
   - name: https
    port: 443
    targetPort: 443
```


The  target  annotation can reference another service, even one in a different namespace. (
