### ISSUE TITLE
create tokenclaim yaml way

### ISSUE THREAD

**Issue by quentinalbertone** [skupperproject/skupper#697]
Hi

I'm trying to create a token claim with yaml file, I tried to follow this doc: https://skupper.io/docs/declarative/tutorial.html#step-3-connect-your-namespaces which tell to create this secret:

```Yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    skupper.io/type: connection-token-request
  name: west-secret
```

---
1- `skupper.io/type: connection-token-request` seems to be related to the `skupper connection-token /tmp/token.yaml` which is deprecated now
2- The secret is afterward populated by skupper, but the secret does not look like the secrets created by `skupper token create --uses 1 /tmp/token.yaml` how can I create a `token-claim` the same way describe in the declarative tutorial

thanks
