### ISSUE TITLE
Policy namespace selection by label is not accepting labels that contain a slash

### ISSUE THREAD

**Issue by hash-d** [skupperproject/skupper#702]
To reproduce:

* Create a namespace with the label `test.skupper.io/test-namespace=policy`
* Add the policy below
* `skupper token create` will fail, whereas it should have worked
* If only `test-namespace=policy` is used, for both the namespace label and policy, token creation works as expected.

```
apiVersion: skupper.io/v1alpha1              
kind: SkupperClusterPolicy                   
metadata:                                    
  name: cluster-policy-sample-01             
spec:                                        
  namespaces:                                
    - "test.skupper.io/test-namespace=policy"
  allowIncomingLinks: true                   
  allowedExposedResources:                   
    - "*"                                    
  allowedOutgoingLinksHostnames: []          
  allowedServices:                           
    - "*"                                    
```

According to the label parsing documentation [1], label keys may have at most one slash.

Additionally, according to [2], no underscores should be accepted on the key part of the label.

[1] https://pkg.go.dev/k8s.io/apimachinery/pkg/labels#Parse
[2] https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
