### ISSUE TITLE
Provide a model YAML file with the minimal permissions to start Skupper for non-admin users or service-accounts.

### ISSUE THREAD

**Issue by rafaelvzago** [skupperproject/skupper#783]
## Scenario 
- A non-admin user/SA needs to start skupper into its respective namespace/project. 

## Case
- Create a service account, one role, and make the role-binding to the service account:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-name
  namespace: namespace-name

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: role-name
  namespace: namespace-name
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: role-binding-name
  namespace: namespace-name
subjects:
- kind: ServiceAccount
  name: service-account-name
  namespace: namespace-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-name
```

*  **Pros**: The S/A will have full permission to a given namespace.
* **Cons**: There is no specific mapping of the needed resources/apiGroups/Verbs that are really a dependency.
* **Objective**: The _cluster-admin_ be able to have precise control of the permissions and map all the needed resources for skupper.
