### ISSUE TITLE
Ingress annotations not being applied to LoadBalancer

### ISSUE THREAD

**Issue by adamtharani** [skupperproject/skupper#824]
Hi there, I'm trying to add annotations to the Ingress LoadBalancer but I don't see them being applied n the created LoadBalancer, am I missing something?

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: skupper-site
  namespace: skupper-site-controller
data:
   ingress-annotations: service.beta.kubernetes.io/do-loadbalancer-name=someName
```
