### ISSUE TITLE
Skupper on mac (arm64)

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#894]
When trying to link skupper sites on mac with m1 chip:

- started minikube (detects and uses docker)
- skupper inits fine (using minikube tunnel)
- skupper token create -t my.yaml cert
- skupper link create my.yaml
- skupper link status
Link link1 not active (Failed to redeem claim: Post https://127.0.0.1:8081/8a97af6e-3e6a-11ed-8763-121329eee648?site-version=1.0.0: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "skupper-site-ca"))

Looking at the cert token:

```
metadata:
  annotations:
    edge-host: 127.0.0.1
    edge-port: "45671"
    inter-router-host: 127.0.0.1
    inter-router-port: "55671"
    skupper.io/generated-by: d8c28935-87a4-4f01-9f93-fd752f38448b
    skupper.io/site-version: 1.0.0
  creationTimestamp: null
```
