### ISSUE TITLE
skupper annotations - Add a name to the port getting exposed

### ISSUE THREAD

**Issue by rmallam** [skupperproject/skupper#947]
I was thinking it will be good to have a name attached to every port that is getting exposed using skupper.  currently if i use skupper annotations to create a skupper service, The service getting created will have ports with something like port8080. Should we add something on the annotations to name each port?

```
  annotations:
    skupper.io/address: tg-marketing-insight-ui
    skupper.io/port: 8443,8080,6379
    skupper.io/proxy: "tcp"
```
to

```
  annotations:
    skupper.io/address: tg-marketing-insight-ui
    skupper.io/port: https:8443,http:8080,redis:6379
    skupper.io/proxy: "tcp"
```
The makes it both readable and easy for declarative implementation while using helm to deploy applications and creating routes by exposing skupper services.
