### ISSUE TITLE
Unable to run skupper command on my local machine due to "exec plugin: invalid apiVersion "client.authentication.k8s.io/v1"" error

### ISSUE THREAD

**Issue by lordgordon** [skupperproject/skupper#994]
When running `skupper` on my local machine against an EKS cluster with AWS SSO authentication, all `skupper` commands using the remote fail due to the following error:

```
exec plugin: invalid apiVersion "client.authentication.k8s.io/v1"
```

## Versions

- Skupper: `1.2.2`
- Kubectl local: `1.26.1`
- Kubectl remote: `1.23.13`
- local OS: macOS Ventura `13.1`

## Kubeconfig

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ***
    server: ***
  name: qa-eks
contexts:
- context:
    cluster: qa-eks
    user: sso-qa
  name: qa-eks
current-context: qa-eks
kind: Config
preferences: {}
users:
- name: sso-qa
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - --region
      - ***
      - eks
      - get-token
      - --cluster-name
      - qa
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
